#!/usr/bin/env python3
"""
export_weights_to_js.py
=======================
Extracts weights from your trained Keras model and generates
a pure-JavaScript neural network inference function.

No TensorFlow.js needed in the extension at all -- runs in any
Chrome MV3 service worker without unsafe-eval.

Usage (run from extension root folder):
    python export_weights_to_js.py

Output:
    models/nn_inference.js   <- drop-in replacement, paste into background.js
"""

import os
import json
import numpy as np
import tensorflow as tf

# -- Paths ----------------------------------------------------------------------
H5_PATH    = "models/keras_model.h5"
OUTPUT_JS  = "models/nn_inference.js"
OUTPUT_JSON = "models/nn_weights.json"

# ------------------------------------------------------------------------------

def extract_dense_weights(model):
    """Extract weights from every Dense + BatchNorm layer."""
    layers_data = []
    for layer in model.layers:
        cfg  = layer.get_config()
        name = layer.name
        w    = layer.get_weights()

        if isinstance(layer, tf.keras.layers.Dense):
            assert len(w) == 2, f"Expected kernel+bias for Dense layer {name}"
            layers_data.append({
                "type":       "dense",
                "name":       name,
                "activation": cfg.get("activation", "linear"),
                "kernel":     w[0].tolist(),   # shape [in, out]
                "bias":       w[1].tolist(),   # shape [out]
            })
            print(f"  [Dense]     {name:20s}  {w[0].shape}  activation={cfg.get('activation')}")

        elif isinstance(layer, tf.keras.layers.BatchNormalization):
            # w = [gamma, beta, moving_mean, moving_variance]
            assert len(w) == 4, f"Expected 4 tensors for BN layer {name}"
            layers_data.append({
                "type":     "batchnorm",
                "name":     name,
                "gamma":    w[0].tolist(),
                "beta":     w[1].tolist(),
                "mean":     w[2].tolist(),
                "variance": w[3].tolist(),
                "epsilon":  cfg.get("epsilon", 1e-3),
            })
            print(f"  [BatchNorm] {name:20s}  units={len(w[0])}")

        elif isinstance(layer, (tf.keras.layers.Dropout,
                                tf.keras.layers.InputLayer)):
            pass  # no weights, skip

    return layers_data


def generate_js(layers_data):
    """Generate a self-contained JS function that runs forward pass."""

    lines = []
    lines.append("/**")
    lines.append(" * nn_inference.js -- Pure-JS Neural Network (no TF.js needed)")
    lines.append(" * Auto-generated by export_weights_to_js.py")
    lines.append(" * Drop the contents of runNeuralNet() into background.js")
    lines.append(" * and remove all TF.js / importScripts references.")
    lines.append(" */")
    lines.append("")
    lines.append("// -- Weights (auto-generated, do not edit manually) --------------------------")
    lines.append("const NN_LAYERS = " + json.dumps(layers_data, separators=(',', ':')) + ";")
    lines.append("")
    lines.append("// -- Activation functions ----------------------------------------------------")
    lines.append("function relu(x)    { return x > 0 ? x : 0; }")
    lines.append("function sigmoid(x) { return 1 / (1 + Math.exp(-x)); }")
    lines.append("")
    lines.append("// -- Forward pass ------------------------------------------------------------")
    lines.append("function runNeuralNet(inputArray) {")
    lines.append("  var x = inputArray.slice(); // copy")
    lines.append("")
    lines.append("  for (var li = 0; li < NN_LAYERS.length; li++) {")
    lines.append("    var L = NN_LAYERS[li];")
    lines.append("")
    lines.append("    if (L.type === 'dense') {")
    lines.append("      var kernel = L.kernel;  // [in, out]")
    lines.append("      var bias   = L.bias;    // [out]")
    lines.append("      var out    = [];")
    lines.append("      for (var j = 0; j < bias.length; j++) {")
    lines.append("        var sum = bias[j];")
    lines.append("        for (var i = 0; i < x.length; i++) {")
    lines.append("          sum += x[i] * kernel[i][j];")
    lines.append("        }")
    lines.append("        if (L.activation === 'relu')    sum = relu(sum);")
    lines.append("        if (L.activation === 'sigmoid') sum = sigmoid(sum);")
    lines.append("        out.push(sum);")
    lines.append("      }")
    lines.append("      x = out;")
    lines.append("")
    lines.append("    } else if (L.type === 'batchnorm') {")
    lines.append("      var eps = L.epsilon || 1e-3;")
    lines.append("      x = x.map(function(val, i) {")
    lines.append("        var xhat = (val - L.mean[i]) / Math.sqrt(L.variance[i] + eps);")
    lines.append("        return L.gamma[i] * xhat + L.beta[i];")
    lines.append("      });")
    lines.append("    }")
    lines.append("  }")
    lines.append("")
    lines.append("  return x[0]; // single sigmoid output = phishing probability")
    lines.append("}")
    lines.append("")
    lines.append("// -- Usage in background.js --------------------------------------------------")
    lines.append("// Replace the entire predict() function body with:")
    lines.append("//")
    lines.append("//   function predict(features) {")
    lines.append("//     var norm = normaliseFeatures(features);")
    lines.append("//     return runNeuralNet(norm);")
    lines.append("//   }")
    lines.append("//")
    lines.append("// And remove: importScripts, loadModel(), tf.loadLayersModel(),")
    lines.append("//             MODEL_URL, modelLoading, and all tf.* references.")

    return "\n".join(lines)


def main():
    print(f"[Export] Loading model from {H5_PATH} ...")
    if not os.path.exists(H5_PATH):
        print(f"[Error] File not found: {H5_PATH}")
        print(f"        Current directory: {os.getcwd()}")
        print("        Run this script from your extension root folder (where manifest.json is).")
        return
        return

    model = tf.keras.models.load_model(H5_PATH)
    model.summary()

    print("\n[Export] Extracting layers:")
    layers_data = extract_dense_weights(model)

    # Save JS file
    js_code = generate_js(layers_data)
    with open(OUTPUT_JS, "w", encoding="utf-8") as f:
        f.write(js_code)
    print(f"\n[Export] Done! JS inference code -> {OUTPUT_JS}")

    # Also save raw JSON weights for reference
    with open(OUTPUT_JSON, "w", encoding="utf-8") as f:
        json.dump(layers_data, f, indent=2)
    print(f"[Export] Done! Raw weights JSON  -> {OUTPUT_JSON}")

    print("\n[Next steps]")
    print("  1. Open models/nn_inference.js")
    print("  2. Copy NN_LAYERS + runNeuralNet() into src/background.js")
    print("  3. Replace predict() body with: return runNeuralNet(normaliseFeatures(features));")
    print("  4. Remove importScripts, loadModel(), MODEL_URL, tf.* references")
    print("  5. Reload extension at chrome://extensions")
    print("  6. No tf.min.js needed at all -- pure JS runs fine in MV3!")


if __name__ == "__main__":
    main()
