#!/usr/bin/env python3
"""
make_background.py
==================
Reads model/nn_weights.json and writes a complete src/background.js
with the neural network weights baked in. No TF.js needed.

Run from your extension root folder:
    python make_background.py
"""
import json, os

WEIGHTS_PATH = "models/nn_weights.json"
NORM_PATH    = "models/normalisation_params.json"
OUTPUT_PATH  = "src/background.js"

# ── Load weights ───────────────────────────────────────────────────────────────
if not os.path.exists(WEIGHTS_PATH):
    print(f"ERROR: {WEIGHTS_PATH} not found.")
    print(f"       Current directory: {os.getcwd()}")
    print("       Run from your extension root folder (where manifest.json is).")
    exit(1)

with open(WEIGHTS_PATH, encoding="utf-8") as f:
    layers = json.load(f)
print("Loaded", len(layers), "layers from", WEIGHTS_PATH)

# ── Load normalisation params ──────────────────────────────────────────────────
if os.path.exists(NORM_PATH):
    with open(NORM_PATH, encoding="utf-8") as f:
        norm = json.load(f)
    mins = norm["feature_mins"]
    maxs = norm["feature_maxs"]
    print("Loaded normalisation params from", NORM_PATH)
else:
    mins = [10, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    maxs = [512, 8, 1, 1, 5, 1, 1, 1, 1, 30]
    print("WARNING: normalisation_params.json not found, using defaults.")

layers_json = json.dumps(layers, separators=(",", ":"))
mins_json   = json.dumps(mins)
maxs_json   = json.dumps(maxs)

# ── Build background.js ────────────────────────────────────────────────────────
js = (
"/**\n"
" * background.js -- Phishing Attack Detection Master (Service Worker)\n"
" * v2.0: Pure-JS neural network. No TF.js, no unsafe-eval required.\n"
" */\n"
"\n"
"// Auto-generated weights from trained Keras model\n"
"var NN_LAYERS = " + layers_json + ";\n"
"\n"
"var FEATURE_MINS = " + mins_json + ";\n"
"var FEATURE_MAXS = " + maxs_json + ";\n"
"\n"
"// Activation functions\n"
"function relu(x)    { return x > 0 ? x : 0; }\n"
"function sigmoid(x) { return 1 / (1 + Math.exp(-x)); }\n"
"\n"
"// Neural network forward pass\n"
"function runNeuralNet(input) {\n"
"  var x = input.slice();\n"
"  for (var li = 0; li < NN_LAYERS.length; li++) {\n"
"    var L = NN_LAYERS[li];\n"
"    if (L.type === 'dense') {\n"
"      var out = [];\n"
"      for (var j = 0; j < L.bias.length; j++) {\n"
"        var sum = L.bias[j];\n"
"        for (var i = 0; i < x.length; i++) { sum += x[i] * L.kernel[i][j]; }\n"
"        if (L.activation === 'relu')    sum = relu(sum);\n"
"        if (L.activation === 'sigmoid') sum = sigmoid(sum);\n"
"        out.push(sum);\n"
"      }\n"
"      x = out;\n"
"    } else if (L.type === 'batchnorm') {\n"
"      var eps = L.epsilon || 1e-3;\n"
"      x = x.map(function(val, i) {\n"
"        var xhat = (val - L.mean[i]) / Math.sqrt(L.variance[i] + eps);\n"
"        return L.gamma[i] * xhat + L.beta[i];\n"
"      });\n"
"    }\n"
"  }\n"
"  return x[0];\n"
"}\n"
"\n"
"// Constants\n"
"var RISK_THRESHOLD_HIGH   = 0.75;\n"
"var RISK_THRESHOLD_MEDIUM = 0.45;\n"
"var DB_NAME    = 'PhishingDetectorDB';\n"
"var DB_VERSION = 1;\n"
"var STORE_NAME = 'detectionLogs';\n"
"var db = null;\n"
"var tabScanCache = {};\n"
"\n"
"// Normalise raw features to [0,1]\n"
"function normaliseFeatures(features) {\n"
"  var raw = [\n"
"    features.urlLength           || 0,\n"
"    features.dotCount            || 0,\n"
"    features.hasAt               || 0,\n"
"    features.isHttps             || 0,\n"
"    features.subdomainCount      || 0,\n"
"    features.isIPAddress         || 0,\n"
"    features.suspiciousTLD       || 0,\n"
"    features.formActionMismatch  || 0,\n"
"    features.hasPasswordField    || 0,\n"
"    features.externalScriptCount || 0,\n"
"  ];\n"
"  return raw.map(function(val, i) {\n"
"    var range = FEATURE_MAXS[i] - FEATURE_MINS[i];\n"
"    if (range === 0) return 0;\n"
"    return Math.min(1, Math.max(0, (val - FEATURE_MINS[i]) / range));\n"
"  });\n"
"}\n"
"\n"
"// Run inference\n"
"function predict(features) {\n"
"  var norm = normaliseFeatures(features);\n"
"  try {\n"
"    return Math.min(1, Math.max(0, runNeuralNet(norm)));\n"
"  } catch(e) {\n"
"    console.warn('[PADM] NN error, using heuristic:', e.message);\n"
"    var weights = [0.08, 0.10, 0.15, -0.12, 0.12, 0.18, 0.14, 0.16, 0.05, 0.04];\n"
"    var score = 0.10;\n"
"    for (var i = 0; i < norm.length; i++) score += norm[i] * weights[i];\n"
"    return Math.min(1, Math.max(0, score));\n"
"  }\n"
"}\n"
"\n"
"// Threat label builder\n"
"function buildThreatLabels(features) {\n"
"  var labels = [];\n"
"  if (features.hasAt)                     labels.push('@ symbol in URL');\n"
"  if (features.isIPAddress)               labels.push('IP address used as domain');\n"
"  if (features.suspiciousTLD)             labels.push('Suspicious TLD');\n"
"  if (features.formActionMismatch)        labels.push('Cross-domain form action');\n"
"  if (features.hasPasswordField)          labels.push('Password field detected');\n"
"  if (features.dotCount > 4)              labels.push('Excessive subdomains');\n"
"  if (features.urlLength > 100)           labels.push('Abnormally long URL');\n"
"  if (!features.isHttps)                  labels.push('No HTTPS');\n"
"  if (features.externalScriptCount > 10)  labels.push('High external script count');\n"
"  return labels;\n"
"}\n"
"\n"
"// Update extension badge\n"
"function updateBadge(tabId, score) {\n"
"  var pct   = Math.round(score * 100);\n"
"  var color = score >= RISK_THRESHOLD_HIGH   ? '#c0392b'\n"
"            : score >= RISK_THRESHOLD_MEDIUM ? '#e67e22'\n"
"            : '#27ae60';\n"
"  chrome.action.setBadgeBackgroundColor({ color: color, tabId: tabId }).catch(function(){});\n"
"  chrome.action.setBadgeText({ text: String(pct), tabId: tabId }).catch(function(){});\n"
"}\n"
"\n"
"// Send desktop notification\n"
"function notifyHighRisk(pageURL, riskScore, threats) {\n"
"  var pct = Math.round(riskScore * 100);\n"
"  var hostname = 'unknown';\n"
"  try { hostname = new URL(pageURL).hostname; } catch(e) {}\n"
"  chrome.notifications.create('padm-' + Date.now(), {\n"
"    type: 'basic',\n"
"    iconUrl: chrome.runtime.getURL('icons/icon48.png'),\n"
"    title: 'Phishing Risk: ' + pct + '%',\n"
"    message: hostname + ' - ' + threats.slice(0, 2).join(' | '),\n"
"    priority: 2,\n"
"  });\n"
"}\n"
"\n"
"// IndexedDB\n"
"function openDatabase() {\n"
"  return new Promise(function(resolve, reject) {\n"
"    var req = indexedDB.open(DB_NAME, DB_VERSION);\n"
"    req.onupgradeneeded = function(e) {\n"
"      var idb = e.target.result;\n"
"      if (!idb.objectStoreNames.contains(STORE_NAME)) {\n"
"        var store = idb.createObjectStore(STORE_NAME, { keyPath: 'id', autoIncrement: true });\n"
"        store.createIndex('timestamp', 'timestamp', { unique: false });\n"
"        store.createIndex('domain',    'domain',    { unique: false });\n"
"        store.createIndex('riskScore', 'riskScore', { unique: false });\n"
"      }\n"
"    };\n"
"    req.onsuccess = function(e) { resolve(e.target.result); };\n"
"    req.onerror   = function(e) { reject(e.target.error);  };\n"
"  });\n"
"}\n"
"\n"
"function logDetection(entry) {\n"
"  if (!db) return Promise.resolve();\n"
"  return new Promise(function(resolve, reject) {\n"
"    var tx = db.transaction(STORE_NAME, 'readwrite');\n"
"    tx.objectStore(STORE_NAME).add(entry);\n"
"    tx.oncomplete = resolve;\n"
"    tx.onerror = function(e) { reject(e.target.error); };\n"
"  });\n"
"}\n"
"\n"
"function queryLogs(fromTS, toTS) {\n"
"  return new Promise(function(resolve, reject) {\n"
"    var tx  = db.transaction(STORE_NAME, 'readonly');\n"
"    var req = tx.objectStore(STORE_NAME).index('timestamp').getAll(IDBKeyRange.bound(fromTS, toTS));\n"
"    req.onsuccess = function(e) { resolve(e.target.result); };\n"
"    req.onerror   = function(e) { reject(e.target.error);  };\n"
"  });\n"
"}\n"
"\n"
"function queryAllLogs() {\n"
"  return new Promise(function(resolve, reject) {\n"
"    var tx  = db.transaction(STORE_NAME, 'readonly');\n"
"    var req = tx.objectStore(STORE_NAME).getAll();\n"
"    req.onsuccess = function(e) { resolve(e.target.result); };\n"
"    req.onerror   = function(e) { reject(e.target.error);  };\n"
"  });\n"
"}\n"
"\n"
"// Core scan handler\n"
"async function handlePageScan(payload, tabId) {\n"
"  var pageURL        = payload.pageURL;\n"
"  var pageTitle      = payload.pageTitle;\n"
"  var timestamp      = payload.timestamp;\n"
"  var featureVectors = payload.featureVectors || [];\n"
"  var pageContext    = payload.pageContext || {};\n"
"  var pageRiskScore  = 0;\n"
"  var suspicious     = [];\n"
"  var allResults     = [];\n"
"\n"
"  for (var i = 0; i < featureVectors.length; i++) {\n"
"    var features = featureVectors[i];\n"
"    var score    = predict(features);\n"
"    var result   = {\n"
"      url:      features.rawURL,\n"
"      hostname: features.hostname || 'unknown',\n"
"      score:    score,\n"
"      threats:  buildThreatLabels(features),\n"
"    };\n"
"    allResults.push(result);\n"
"    if (score >= RISK_THRESHOLD_MEDIUM) suspicious.push(result);\n"
"    if (score > pageRiskScore) pageRiskScore = score;\n"
"  }\n"
"\n"
"  if (pageContext.formActionMismatch)\n"
"    pageRiskScore = Math.max(pageRiskScore, 0.55);\n"
"  if (pageContext.hasPasswordField && !pageURL.startsWith('https'))\n"
"    pageRiskScore = Math.max(pageRiskScore, 0.65);\n"
"  pageRiskScore = Math.min(1, pageRiskScore);\n"
"\n"
"  var category = pageRiskScore >= RISK_THRESHOLD_HIGH   ? 'phishing'\n"
"               : pageRiskScore >= RISK_THRESHOLD_MEDIUM ? 'suspicious'\n"
"               : 'safe';\n"
"\n"
"  var domain = 'unknown';\n"
"  try { domain = new URL(pageURL).hostname; } catch(e) {}\n"
"\n"
"  var scanResult = {\n"
"    pageURL: pageURL, pageTitle: pageTitle, timestamp: timestamp,\n"
"    riskScore: pageRiskScore, category: category,\n"
"    suspicious: suspicious, allResults: allResults,\n"
"    pageContext: pageContext, totalLinks: featureVectors.length, domain: domain,\n"
"  };\n"
"  tabScanCache[tabId] = scanResult;\n"
"\n"
"  if (pageRiskScore >= RISK_THRESHOLD_MEDIUM) {\n"
"    await logDetection({\n"
"      pageURL: pageURL, pageTitle: pageTitle, timestamp: timestamp,\n"
"      riskScore: pageRiskScore, category: category, domain: domain,\n"
"      threats:         suspicious.flatMap(function(s) { return s.threats; }),\n"
"      suspiciousURLs:  suspicious.map(function(s) { return s.url; }),\n"
"      totalLinks:      featureVectors.length,\n"
"      suspiciousCount: suspicious.length,\n"
"    });\n"
"  }\n"
"\n"
"  if (pageRiskScore >= RISK_THRESHOLD_HIGH) {\n"
"    var topThreats = suspicious.flatMap(function(s) { return s.threats; }).slice(0, 5);\n"
"    chrome.tabs.sendMessage(tabId, {\n"
"      type: 'PHISHING_ALERT', riskScore: pageRiskScore, threats: topThreats,\n"
"    }).catch(function(){});\n"
"    notifyHighRisk(pageURL, pageRiskScore, topThreats);\n"
"  }\n"
"\n"
"  updateBadge(tabId, pageRiskScore);\n"
"  console.log('[PADM] Scanned:', domain, 'score:', (pageRiskScore * 100).toFixed(1) + '%', category);\n"
"}\n"
"\n"
"// Message router\n"
"chrome.runtime.onMessage.addListener(function(message, sender, sendResponse) {\n"
"  var tabId = sender.tab ? sender.tab.id : null;\n"
"\n"
"  if (message.type === 'PAGE_SCAN') {\n"
"    handlePageScan(message, tabId);\n"
"    sendResponse({ received: true });\n"
"    return false;\n"
"  }\n"
"\n"
"  if (message.type === 'GET_SCAN_RESULT') {\n"
"    chrome.tabs.query({ active: true, currentWindow: true }, function(tabs) {\n"
"      var id = tabs[0] ? tabs[0].id : null;\n"
"      sendResponse(tabScanCache[id] || null);\n"
"    });\n"
"    return true;\n"
"  }\n"
"\n"
"  if (message.type === 'GET_LOGS') {\n"
"    var p = (message.from && message.to)\n"
"          ? queryLogs(message.from, message.to)\n"
"          : queryAllLogs();\n"
"    p.then(function(logs) { sendResponse({ logs: logs }); })\n"
"     .catch(function(err)  { sendResponse({ error: err.message }); });\n"
"    return true;\n"
"  }\n"
"\n"
"  sendResponse({ error: 'Unknown message type' });\n"
"  return false;\n"
"});\n"
"\n"
"// Initialise\n"
"(async function init() {\n"
"  db = await openDatabase();\n"
"  console.log('[PADM] Service worker initialised. Inference: Neural Network (pure JS, no TF.js)');\n"
"  console.log('[PADM] Layers:', NN_LAYERS.length, '| MINS:', FEATURE_MINS, '| MAXS:', FEATURE_MAXS);\n"
"})();\n"
"\n"
"chrome.runtime.onStartup.addListener(async function() {\n"
"  if (!db) db = await openDatabase();\n"
"});\n"
)

with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
    f.write(js)

size = os.path.getsize(OUTPUT_PATH)
print("Done! Written to", OUTPUT_PATH, "(", size, "bytes )")
print("First line:", open(OUTPUT_PATH, encoding="utf-8").readline().strip())
print()
print("Next steps:")
print("  1. Go to chrome://extensions")
print("  2. Click reload on your extension")
print("  3. Service worker should show: Inference: Neural Network (pure JS)")
